export type ResourceType = 'article' | 'book' | 'video'

export interface LearningResource {
  id: string
  title: string
  type: ResourceType
  summary: string
  tags: string[]
  week: number
  href?: string
  source?: string
  author?: string
  publisher?: string
  hotScore?: number
  qualityScore?: number
  caseSlug?: string
}

export const resourceTypes: { id: ResourceType | 'all'; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'article', label: '文章' },
  { id: 'book', label: '书籍' },
  { id: 'video', label: '视频' },
]

export const resources: LearningResource[] = [
  {
    id: 'r1',
    title: 'AI 学习路径总览：先做什么',
    type: 'article',
    summary: '从目标岗位倒推 12 周节奏，先搭框架再做实战。',
    tags: ['D2', 'W1'],
    week: 1,
  },
  {
    id: 'r2',
    title: 'AI PM 起步常见误区',
    type: 'article',
    summary: '避免“只学工具不学判断”的低效路径。',
    tags: ['D1', 'W1'],
    week: 1,
  },
  {
    id: 'r3',
    title: 'AI PM 入门知识地图',
    type: 'video',
    summary: '建立 AI 产品经理应具备的能力全景。',
    tags: ['D1', 'W1'],
    week: 1,
    source: 'Bilibili',
    hotScore: 82,
    qualityScore: 78,
  },
  {
    id: 'r4',
    title: 'Good Strategy Bad Strategy',
    type: 'book',
    summary: '战略判断与取舍，适合 W2/W3 的定位与路径规划。',
    tags: ['D2', 'W2'],
    week: 2,
    author: 'Richard Rumelt',
    publisher: 'Currency',
    source: '图书',
  },
  {
    id: 'r5',
    title: '产品战略拆解：如何做取舍',
    type: 'article',
    summary: '把“方向正确”拆成可验证的行动和里程碑。',
    tags: ['D2', 'W2'],
    week: 2,
  },
  {
    id: 'r6',
    title: 'AI 战略案例复盘',
    type: 'video',
    summary: '从业务目标、技术可行性、资源投入三角看战略。',
    tags: ['D2', 'W2'],
    week: 2,
    source: 'Bilibili',
    hotScore: 76,
    qualityScore: 74,
  },
  {
    id: 'r7',
    title: 'ToG 智慧招商增长方法',
    type: 'article',
    summary: '从“功能上线”到“成交增长”的产品闭环。',
    tags: ['D2', 'W3'],
    week: 3,
  },
  {
    id: 'r8',
    title: '增长指标体系设计',
    type: 'book',
    summary: '构建北极星指标与分层漏斗指标。',
    tags: ['D2', 'W3'],
    week: 3,
    source: '图书',
  },
  {
    id: 'r9',
    title: 'ToG 产品增长复盘',
    type: 'video',
    summary: '过亿成交背后的产品逻辑、指标体系与运营动作。',
    tags: ['D2', 'W3'],
    week: 3,
    source: 'Bilibili',
    hotScore: 91,
    qualityScore: 88,
    caseSlug: 'smart-investment',
  },
  {
    id: 'r10',
    title: 'RAG 立项前三问',
    type: 'article',
    summary: '从业务边界、数据质量、评测口径三层判断“该不该做”。',
    tags: ['D1', 'W4'],
    week: 4,
    href: 'https://www.woshipm.com/ai/6348259.html',
  },
  {
    id: 'r11',
    title: '企业知识库建设实务',
    type: 'book',
    summary: '知识切分、索引、召回、更新机制的工程化实践。',
    tags: ['D1', 'W4'],
    week: 4,
    source: '图书',
  },
  {
    id: 'r12',
    title: 'RAG 评测与调优',
    type: 'video',
    summary: '从召回到生成的质量评测闭环。',
    tags: ['D1', 'W4'],
    week: 4,
    source: 'Bilibili',
    hotScore: 84,
    qualityScore: 86,
  },
  {
    id: 'r13',
    title: '智能体任务编排方法',
    type: 'article',
    summary: '拆分角色、工具和流程，避免 Agent 失控。',
    tags: ['D1', 'W5'],
    week: 5,
  },
  {
    id: 'r14',
    title: 'Agent 产品设计',
    type: 'book',
    summary: '定义边界、交互反馈、人机协作与回滚策略。',
    tags: ['D1', 'W5'],
    week: 5,
    source: '图书',
  },
  {
    id: 'r15',
    title: 'Empowered',
    type: 'video',
    summary: '组织能力与产品能力协同的经典观点解读。',
    tags: ['D5', 'W5'],
    week: 5,
    source: 'Bilibili',
    hotScore: 79,
    qualityScore: 80,
  },
  {
    id: 'r16',
    title: '招投标智能体案例讲解',
    type: 'video',
    summary: '从合规约束到 Agent 设计，拆解高风险场景落地方法。',
    tags: ['D1', 'W5'],
    week: 5,
    source: 'Bilibili',
    hotScore: 95,
    qualityScore: 92,
    caseSlug: 'bid-agent',
  },
  {
    id: 'r17',
    title: 'AI 评测框架实战',
    type: 'article',
    summary: '离线集、线上灰度、门禁规则的组合设计。',
    tags: ['D3', 'W6'],
    week: 6,
  },
  {
    id: 'r18',
    title: '机器学习系统测试',
    type: 'book',
    summary: '把 ML/LLM 测试体系化，减少回归风险。',
    tags: ['D3', 'W6'],
    week: 6,
    source: '图书',
  },
  {
    id: 'r19',
    title: 'Eval 指标设计拆解',
    type: 'video',
    summary: '覆盖准确率、稳定性、体验与业务价值。',
    tags: ['D3', 'W6'],
    week: 6,
    source: 'Bilibili',
    hotScore: 73,
    qualityScore: 79,
  },
  {
    id: 'r20',
    title: '单位经济模型搭建',
    type: 'article',
    summary: '从 token、调用链到业务 ROI 的成本核算。',
    tags: ['D6', 'W7'],
    week: 7,
  },
  {
    id: 'r21',
    title: '产品成本管理',
    type: 'book',
    summary: '用财务与经营思维看产品投入产出。',
    tags: ['D6', 'W7'],
    week: 7,
    source: '图书',
  },
  {
    id: 'r22',
    title: '推理成本优化方法',
    type: 'video',
    summary: '缓存、路由、降级与模型分层。',
    tags: ['D6', 'W7'],
    week: 7,
    source: 'Bilibili',
    hotScore: 78,
    qualityScore: 82,
  },
  {
    id: 'r23',
    title: 'AI 合规清单',
    type: 'article',
    summary: '内容安全、隐私保护、审计留痕的最小合规集。',
    tags: ['D3', 'W8'],
    week: 8,
  },
  {
    id: 'r24',
    title: '数据治理手册',
    type: 'book',
    summary: '规范数据生命周期，确保可追溯与可管控。',
    tags: ['D3', 'W8'],
    week: 8,
    source: '图书',
  },
  {
    id: 'r25',
    title: '高风险场景合规案例',
    type: 'video',
    summary: 'ToB/ToG 环境下的风控设计经验。',
    tags: ['D3', 'W8'],
    week: 8,
    source: 'Bilibili',
    hotScore: 81,
    qualityScore: 84,
  },
  {
    id: 'r26',
    title: '跨团队协作机制设计',
    type: 'article',
    summary: '产品、算法、研发、销售的节奏对齐方法。',
    tags: ['D5', 'W9'],
    week: 9,
  },
  {
    id: 'r27',
    title: 'Empowered',
    type: 'book',
    summary: '产品组织与团队机制，适合 W9 协作周。',
    tags: ['D5', 'W9'],
    week: 9,
    author: 'Marty Cagan',
    source: '图书',
  },
  {
    id: 'r28',
    title: '组织协同案例拆解',
    type: 'video',
    summary: '目标管理、责任分工与决策节奏。',
    tags: ['D5', 'W9'],
    week: 9,
    source: 'Bilibili',
    hotScore: 71,
    qualityScore: 75,
  },
  {
    id: 'r29',
    title: '复盘框架：从项目到能力',
    type: 'article',
    summary: '每周复盘模板，把经验转为可复用资产。',
    tags: ['D4', 'W10'],
    week: 10,
  },
  {
    id: 'r30',
    title: '原则',
    type: 'book',
    summary: '高压决策和持续改进的底层原则。',
    tags: ['D4', 'W10'],
    week: 10,
    author: 'Ray Dalio',
    source: '图书',
  },
  {
    id: 'r31',
    title: '项目复盘实战课',
    type: 'video',
    summary: '从事实到机制，沉淀团队知识资产。',
    tags: ['D4', 'W10'],
    week: 10,
    source: 'Bilibili',
    hotScore: 77,
    qualityScore: 81,
  },
  {
    id: 'r32',
    title: 'AI PM 面试四步法',
    type: 'article',
    summary: '把项目经历讲成业务结果：场景 -> 方案 -> 兜底 -> 数据闭环。',
    tags: ['D5', 'W11'],
    week: 11,
    href: 'https://www.woshipm.com/share/6402013.html',
  },
  {
    id: 'r33',
    title: '金字塔原理',
    type: 'book',
    summary: '提升结构化表达，适合简历与面试叙事。',
    tags: ['D5', 'W11'],
    week: 11,
    author: 'Barbara Minto',
    source: '图书',
  },
  {
    id: 'r34',
    title: '高质量面试表达示例',
    type: 'video',
    summary: '同一项目如何说出 PM 版与总监版差异。',
    tags: ['D5', 'W11'],
    week: 11,
    source: 'Bilibili',
    hotScore: 88,
    qualityScore: 89,
  },
  {
    id: 'r35',
    title: '职业发展路线图设计',
    type: 'article',
    summary: '从当前岗位到目标岗位，定义下一阶段能力杠杆。',
    tags: ['D4', 'W12'],
    week: 12,
  },
  {
    id: 'r36',
    title: '思考，快与慢',
    type: 'book',
    summary: '强化判断质量与决策偏差识别能力。',
    tags: ['D4', 'W12'],
    week: 12,
    author: 'Daniel Kahneman',
    source: '图书',
  },
  {
    id: 'r37',
    title: '年度成长闭环复盘',
    type: 'video',
    summary: '如何把 12 周成果沉淀为长期竞争力。',
    tags: ['D4', 'W12'],
    week: 12,
    source: 'Bilibili',
    hotScore: 69,
    qualityScore: 77,
  },
  {
    id: 'r38',
    title: '大模型应用开发：从 Prompt 到 RAG 的完整路径',
    type: 'article',
    summary: '系统梳理大模型应用落地链路，适合建立端到端认知。',
    tags: ['D1', 'W4'],
    week: 4,
    source: '机器之心',
    href: 'https://www.jiqizhixin.com',
  },
  {
    id: 'r39',
    title: '智能体（Agent）设计模式：规划、执行与反思',
    type: 'article',
    summary: '介绍 ReAct、Plan-Execute、Reflection 等常见 Agent 模式。',
    tags: ['D1', 'W5'],
    week: 5,
    source: 'LangChain Blog',
    href: 'https://blog.langchain.dev',
  },
  {
    id: 'r40',
    title: 'Function Calling 与 Tool Use 在业务系统中的实践',
    type: 'article',
    summary: '解释如何把外部工具接入模型，减少幻觉并提升可控性。',
    tags: ['D1', 'W5'],
    week: 5,
    source: 'OpenAI',
    href: 'https://platform.openai.com/docs',
  },
  {
    id: 'r41',
    title: 'RAG 评估体系：召回、相关性与答案可信度',
    type: 'article',
    summary: '给出可执行的 RAG 指标框架，帮助评审与优化闭环。',
    tags: ['D3', 'W6'],
    week: 6,
    source: 'Weights & Biases',
    href: 'https://wandb.ai/site/articles',
  },
  {
    id: 'r42',
    title: '企业级大模型治理：安全、合规与审计',
    type: 'article',
    summary: '聚焦政企场景中数据边界、权限与审计留痕机制。',
    tags: ['D3', 'W8'],
    week: 8,
    source: '腾讯云开发者',
    href: 'https://cloud.tencent.com/developer',
  },
  {
    id: 'r43',
    title: '多智能体协同（Multi-Agent）在复杂流程中的价值',
    type: 'article',
    summary: '讨论多 Agent 协作分工、冲突控制和稳定性设计。',
    tags: ['D5', 'W9'],
    week: 9,
    source: 'arXiv',
    href: 'https://arxiv.org',
  },
  {
    id: 'r44',
    title: 'LLMOps 实践：大模型应用的发布、监控与回滚',
    type: 'article',
    summary: '把大模型应用纳入工程体系，保障持续交付与稳定运行。',
    tags: ['D6', 'W7'],
    week: 7,
    source: 'Hugging Face',
    href: 'https://huggingface.co/blog',
  },
  {
    id: 'r45',
    title: '智能体产品面试题库：如何讲清技术与业务取舍',
    type: 'article',
    summary: '面向 AI PM/总监，沉淀智能体落地中的关键面试表达。',
    tags: ['D5', 'W11'],
    week: 11,
    source: '人人都是产品经理',
    href: 'https://www.woshipm.com',
  },
]
